import { Dashboard, Subject, Task } from "@/types";

const dashId = "default";

// Helper functions to generate dynamic relative dates
function getOffsetDate(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function getOffsetDateTime(days: number, timeStr: string): string {
  const dateStr = getOffsetDate(days);
  return `${dateStr}T${timeStr}`;
}

const dObj = new Date();
const monthName = dObj.toLocaleDateString("en-US", { month: "long" });
const currentStatusDateStr = `Current Status — ${monthName} ${dObj.getDate()}, ${dObj.getFullYear()}`;

export const defaultDashboards: Dashboard[] = [
  {
    id: dashId,
    name: "Study Buddy Syllabus Workspace — Master Plan",
    description: "Your comprehensive roadmap combining theoretical foundations, projects, coding practice, and general knowledge tracks.",
    createdAt: new Date().toISOString(),
    isDefault: true,
    target: "Target: 100% syllabus coverage & peak practice readiness",
    statusOverview: currentStatusDateStr,
  },
];

export const defaultSubjects: Subject[] = [
  {
    id: "s1",
    name: "Linear Algebra",
    block: "Block 1 - GATE",
    daysPlanned: 10,
    timeline: "Completed",
    status: "Completed",
    percentage: 100,
    pendingTopics: "—",
    completedTopics: "All standard syllabus",
    weightage: "4-5 Marks",
    resource: "GoClasses / NPTEL",
  },
  {
    id: "s2",
    name: "Calculus",
    block: "Block 1 - GATE",
    daysPlanned: 10,
    timeline: "Completed",
    status: "Completed",
    percentage: 100,
    pendingTopics: "—",
    completedTopics: "Limits, continuity, differentiability, integration",
    weightage: "3-4 Marks",
    resource: "GoClasses / NPTEL",
  },
  {
    id: "s3",
    name: "Probability & Statistics",
    block: "Block 1 - GATE",
    daysPlanned: 13,
    timeline: "Ongoing",
    status: "In Progress",
    percentage: 70,
    pendingTopics: "Distributions, CLT, Normal, E[X]/Var[X]",
    completedTopics: "Bayes theorem, conditional probability, random variables",
    weightage: "6–8 Marks",
    resource: "GoClasses / GateOverflow",
  },
  {
    id: "s4",
    name: "Statistics (GATE DA)",
    block: "Block 1 - GATE",
    daysPlanned: 10,
    timeline: "Upcoming",
    status: "Not Started",
    percentage: 0,
    pendingTopics: "Full course — starts after Probability",
    weightage: "5-6 Marks",
    resource: "NPTEL / GFG",
  },
  {
    id: "s5",
    name: "Discrete Mathematics",
    block: "Block 1 - GATE",
    daysPlanned: 18,
    timeline: "Upcoming",
    status: "Not Started",
    percentage: 0,
    pendingTopics: "Largest math unit — 18 days planned",
    weightage: "7–10 Marks",
    resource: "GoClasses / Rosen",
  },
  {
    id: "s6",
    name: "DBMS",
    block: "Block 1 - GATE",
    daysPlanned: 13,
    timeline: "Ongoing",
    status: "In Progress",
    percentage: 70,
    pendingTopics: "B+ Trees, Advanced SQL, Transactions",
    completedTopics: "Relational model, ER design, Normalization",
    weightage: "7–10 Marks",
    resource: "GoClasses / Korth",
  },
  {
    id: "s7",
    name: "Operating Systems",
    block: "Block 1 - GATE",
    daysPlanned: 18,
    timeline: "Ongoing",
    status: "In Progress",
    percentage: 15,
    pendingTopics: "Scheduling, Sync, Deadlock, Memory, FS",
    completedTopics: "Introduction & Process concepts",
    weightage: "8–12 Marks",
    resource: "GoClasses / Galvin",
  },
  {
    id: "s8",
    name: "Networks / TOC / CD / COA / DL",
    block: "Block 1 - GATE",
    daysPlanned: 42,
    timeline: "Upcoming",
    status: "Not Started",
    percentage: 0,
    pendingTopics: "All sequentials",
    weightage: "30-35 Marks",
    resource: "Standard textbooks / PYQs",
  },
  {
    id: "s9",
    name: "ML + AI (GATE DA)",
    block: "Block 1 - GATE",
    daysPlanned: 10,
    timeline: "Upcoming",
    status: "Not Started",
    percentage: 0,
    pendingTopics: "Last 10 days of November",
    weightage: "DA specific",
    resource: "GFG / algomaster",
  },
  {
    id: "s10",
    name: "DSA & Programming",
    block: "DSA",
    daysPlanned: 120,
    timeline: "Ongoing Daily",
    status: "In Progress",
    percentage: 35,
    pendingTopics: "LL, Stacks, Queues, Trees, Heaps, Graphs, DP",
    completedTopics: "Arrays, 2-ptr, sliding window, binary search done",
    weightage: "15–20 Marks",
    resource: "algomaster.io / Leetcode",
  },
  {
    id: "s11",
    name: "System Design - HLD",
    block: "Block 2 - Placements",
    daysPlanned: 16,
    timeline: "Ongoing",
    status: "In Progress",
    percentage: 50,
    pendingTopics: "Sketch HLDs, design services (Twitter, S3, Rate Limiter)",
    completedTopics: "CAP Theorem, CDN, Sharding, Replication",
    weightage: "HLD Interviews",
    resource: "algomaster.io",
  },
  {
    id: "s12",
    name: "Low Level Design (LLD)",
    block: "Block 2 - Placements",
    daysPlanned: 18,
    timeline: "Upcoming",
    status: "Not Started",
    percentage: 0,
    pendingTopics: "SOLID principles, Design patterns, Interview problems (Parking Lot)",
    weightage: "LLD Interviews",
    resource: "algomaster.io",
  },
  {
    id: "s13",
    name: "Concurrency",
    block: "Block 2 - Placements",
    daysPlanned: 11,
    timeline: "Upcoming",
    status: "Not Started",
    percentage: 0,
    pendingTopics: "Threading, mutex, locks, deadlock conditions, async patterns",
    weightage: "Concurrency Rounds",
    resource: "algomaster.io",
  },
];

export const defaultTasks: Task[] = [
  {
    id: "t1_1",
    dashboardId: dashId,
    subjectId: "s3",
    title: "Probability: Bayes theorem & total probability",
    description: "Review Bayes theorem formulation, solve 10 classic conditional probability problems",
    date: getOffsetDate(-2),
    category: "Block 1 - GATE",
    status: "Completed",
    priority: "High",
    notes: "Solidified conditional formulas. Reached 85% accuracy on basic textbook questions.",
    timeSpentMinutes: 90,
    timeLogs: [
      { id: "l1", minutes: 90, note: "Read notes and solved 10 standard Bayes theorem problems", loggedAt: getOffsetDateTime(-2, "10:00:00Z") }
    ],
    attachments: [],
    boardColumnId: "completed",
  },
  {
    id: "t1_2",
    dashboardId: dashId,
    subjectId: "s11",
    title: "System Design: CAP Theorem, PACELC, consistency models",
    description: "Study partition tolerance, consistency guarantees, and quorum writes/reads.",
    date: getOffsetDate(-2),
    category: "Block 2 - Placements",
    status: "Completed",
    priority: "High",
    notes: "Learned consistency trade-offs. Took active notes on quorum formulas (W + R > N).",
    timeSpentMinutes: 75,
    timeLogs: [
      { id: "l2", minutes: 75, note: "Finished HLD theory module", loggedAt: getOffsetDateTime(-2, "18:00:00Z") }
    ],
    attachments: [],
    boardColumnId: "completed",
  },
  {
    id: "t1_3",
    dashboardId: dashId,
    subjectId: "s10",
    title: "Bit Manipulation: 3 standard problems",
    description: "Solve 3 bit manip tasks: count set bits, single number I, find non-repeating number.",
    date: getOffsetDate(-2),
    category: "DSA",
    status: "Completed",
    priority: "Medium",
    notes: "Used XOR tricks effectively.",
    timeSpentMinutes: 45,
    timeLogs: [
      { id: "l3", minutes: 45, note: "Solved on LeetCode", loggedAt: getOffsetDateTime(-2, "08:00:00Z") }
    ],
    attachments: [],
    boardColumnId: "completed",
  },
  {
    id: "t2_1",
    dashboardId: dashId,
    subjectId: "s3",
    title: "Prob: Random variables, PMF, PDF, CDF, Expectation & Variance",
    description: "Study random variable maps, continuous vs discrete. Define expectation formulas and property checks.",
    date: getOffsetDate(-1),
    category: "Block 1 - GATE",
    status: "Completed",
    priority: "High",
    notes: "Revised continuous expectation. Solved 4 standard calculus-based integration PDFs.",
    timeSpentMinutes: 120,
    timeLogs: [
      { id: "l4", minutes: 120, note: "Math derivations and textbook reading", loggedAt: getOffsetDateTime(-1, "11:00:00Z") }
    ],
    attachments: [],
    boardColumnId: "completed",
  },
  {
    id: "t2_2",
    dashboardId: dashId,
    subjectId: "s11",
    title: "System Design: Sharding, replication, CDN",
    description: "Learn partition keys, consistent hashing, master-slave replication models, and edge caching.",
    date: getOffsetDate(-1),
    category: "Block 2 - Placements",
    status: "In Progress",
    priority: "High",
    notes: "Practiced consistent hashing ring diagram. Need to review replica lag scenario.",
    timeSpentMinutes: 60,
    timeLogs: [
      { id: "l5", minutes: 60, note: "Watched CDN and consistent hashing videos", loggedAt: getOffsetDateTime(-1, "19:00:00Z") }
    ],
    attachments: [],
    boardColumnId: "in_progress",
  },
  {
    id: "t2_3",
    dashboardId: dashId,
    subjectId: "s10",
    title: "Bit Manipulation: 4 problems",
    description: "Complete remaining Bit manipulation questions on algomaster.io.",
    date: getOffsetDate(-1),
    category: "DSA",
    status: "Completed",
    priority: "Medium",
    notes: "Completed standard pattern! Set checkbox to Done.",
    timeSpentMinutes: 50,
    timeLogs: [
      { id: "l6", minutes: 50, note: "LeetCode submission completed successfully", loggedAt: getOffsetDateTime(-1, "07:30:00Z") }
    ],
    attachments: [],
    boardColumnId: "completed",
  },
  {
    id: "t3_1",
    dashboardId: dashId,
    subjectId: "s3",
    title: "REVISION: Prob PYQs (10 Qs) & Error notebook",
    description: "Re-solve 10 high-weightage PYQs from past 5 years. Log mistakes in error tracker.",
    date: getOffsetDate(0),
    category: "Block 1 - GATE",
    status: "In Progress",
    priority: "High",
    notes: "Done 6 out of 10. Found a tricky Bayes distribution integration problem.",
    timeSpentMinutes: 60,
    timeLogs: [
      { id: "l7", minutes: 60, note: "Solved 6 PYQs during early morning slot.", loggedAt: getOffsetDateTime(0, "09:00:00Z") }
    ],
    attachments: [],
    boardColumnId: "in_progress",
  },
  {
    id: "t3_2",
    dashboardId: dashId,
    subjectId: "s11",
    title: "Sketch 2 SD designs from memory & review HLD notes",
    description: "Attempt offline sketch of URL Shortener & CDN architecture from scratch.",
    date: getOffsetDate(0),
    category: "Block 2 - Placements",
    status: "Not Started",
    priority: "High",
    notes: "",
    timeSpentMinutes: 0,
    timeLogs: [],
    attachments: [],
    boardColumnId: "today",
  },
  {
    id: "t3_3",
    dashboardId: dashId,
    subjectId: "s10",
    title: "Re-solve 3 weak bit manip problems",
    description: "Go over complex bitmasking question with multiple active pointers.",
    date: getOffsetDate(0),
    category: "DSA",
    status: "Not Started",
    priority: "Low",
    notes: "",
    timeSpentMinutes: 0,
    timeLogs: [],
    attachments: [],
    boardColumnId: "today",
  },
  {
    id: "t4_1",
    dashboardId: dashId,
    subjectId: "s3",
    title: "Prob: Binomial, Poisson, Geometric distributions",
    description: "Understand formulas, condition criteria, and expectation values. Solve 6 standard problems.",
    date: getOffsetDate(1),
    category: "Block 1 - GATE",
    status: "Not Started",
    priority: "High",
    notes: "",
    timeSpentMinutes: 0,
    timeLogs: [],
    attachments: [],
    boardColumnId: "today",
  },
  {
    id: "t4_2",
    dashboardId: dashId,
    subjectId: "s11",
    title: "SD: Design URL Shortener — hashing, DB, scale",
    description: "Design fully scalable URL Shortener with analytics pipeline.",
    date: getOffsetDate(1),
    category: "Block 2 - Placements",
    status: "Not Started",
    priority: "High",
    notes: "",
    timeSpentMinutes: 0,
    timeLogs: [],
    attachments: [],
    boardColumnId: "today",
  },
  {
    id: "t4_3",
    dashboardId: dashId,
    subjectId: "s10",
    title: "LL: Reversal, merge two sorted lists",
    description: "Implement iterative & recursive approaches with complete time-space reviews.",
    date: getOffsetDate(1),
    category: "DSA",
    status: "Not Started",
    priority: "Medium",
    notes: "",
    timeSpentMinutes: 0,
    timeLogs: [],
    attachments: [],
    boardColumnId: "today",
  },
  {
    id: "t5_1",
    dashboardId: dashId,
    subjectId: "s3",
    title: "Prob: Exponential, Normal distributions, CLT, Standardisation",
    description: "Derive normal bell curve parameters, central limit theorem criteria. Prob Done ✅",
    date: getOffsetDate(2),
    category: "Block 1 - GATE",
    status: "Completed",
    priority: "High",
    notes: "Finished Prob Block syllabus! Extremely solid command.",
    timeSpentMinutes: 110,
    timeLogs: [
      { id: "l8", minutes: 110, note: "Full derivation session", loggedAt: getOffsetDateTime(2, "12:00:00Z") }
    ],
    attachments: [],
    boardColumnId: "completed",
  },
  {
    id: "t5_2",
    dashboardId: dashId,
    subjectId: "s11",
    title: "SD: Design Rate Limiter — token bucket, sliding window",
    description: "Understand sliding window log, token bucket, and distributed locking.",
    date: getOffsetDate(2),
    category: "Block 2 - Placements",
    status: "Not Started",
    priority: "Medium",
    notes: "",
    timeSpentMinutes: 0,
    timeLogs: [],
    attachments: [],
    boardColumnId: "today",
  },
  {
    id: "t5_3",
    dashboardId: dashId,
    subjectId: "s10",
    title: "LL: Fast-slow pointer, cycle detection",
    description: "Solve Floyd's cycle finding algorithm and return the head of the list cycle.",
    date: getOffsetDate(2),
    category: "DSA",
    status: "Not Started",
    priority: "Medium",
    notes: "",
    timeSpentMinutes: 0,
    timeLogs: [],
    attachments: [],
    boardColumnId: "today",
  }
];

export function getInitialDefaultData() {
  const formattedTasks = defaultTasks.map((t, idx) => {
    const taskIdVal = `TSK-${String(idx + 1).padStart(3, "0")}`;
    return {
      ...t,
      taskId: t.taskId || t.taskid || taskIdVal,
      taskid: t.taskId || t.taskid || taskIdVal,
    };
  });

  return {
    dashboards: defaultDashboards,
    subjects: defaultSubjects,
    tasks: formattedTasks,
  };
}
