export const FEATURE_FLAGS = {
  ENABLE_AI_IMPORTER: true,
  ENABLE_TIME_TRACKING: true,
  ENABLE_CUSTOM_CSS: true,
} as const;

export const VALIDATION_LIMITS = {
  TASK_TITLE_MAX: 100,
  TASK_NOTES_MAX: 250,
  TASK_DESC_MAX: 200,
  PROFILE_NAME_MAX: 250,
  FILE_NAME_MAX: 60,
  RESOURCE_STRING_MAX: 80,
  SUBJECT_NAME_MAX: 40,
  SUBJECT_TIMELINE_MAX: 30,
  SUBJECT_WEIGHTAGE_MAX: 20,
  SUBJECT_PENDING_MAX: 250,
  FIRST_NAME_MAX: 15,
  LAST_NAME_MAX: 15,
  MOBILE_DIGITS: 10,
  ADDRESS_BIO_MAX: 250,
} as const;
